modLoader="javafml"
loaderVersion="[28,)"
license="All Rights Reserved"

logoFile="trapdoorslogo.png"
[[mods]]
modId="mcwtrpdoors"
version="1.0.7"
displayName="Macaw's Trapdoors"
displayURL="https://www.curseforge.com/minecraft/mc-mods/macaws-trapdoors"
updateJSONURL="https://raw.githubusercontent.com/sketchmacaw/macawsmods/master/trapdoors.json"
credits=""
authors="Sketch Macaw"
description="Adds lots of Trapdoors! With vanila and unique styles."
