modLoader="javafml"
loaderVersion="[28,)"
license="MIT"

logoFile="trapdoorslogo.png"
[[mods]]
modId="mcwtrpdoors"
version="1.0.9"
displayName="Macaw's Trapdoors"
displayURL="https://www.curseforge.com/minecraft/mc-mods/macaws-trapdoors"
updateJSONURL="https://raw.githubusercontent.com/sketchmacaw/macawsmods/master/trapdoors.json"
credits=""
authors="Sketch Macaw & Peachy Macaw"
description="Adds lots of different Trapdoors! With vanila and unique styles."